<a href="https://colab.research.google.com/github/AhmadSyahreza/Katanya-kami-lomba/blob/main/Awal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Katanya Kami Lomba

Notebook ini digunakan untuk coding dan analisis data.

In [ ]:
!pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train1 = pd.read_csv('/content/drive/MyDrive/Lomba Data/train.csv')
test1 = pd.read_csv('/content/drive/MyDrive/Lomba Data/test.csv')
holidays = pd.read_csv('/content/drive/MyDrive/Lomba Data/holidays.csv')
movies = pd.read_csv('/content/drive/MyDrive/Lomba Data/movies.csv')
ticket_prices = pd.read_csv('/content/drive/MyDrive/Lomba Data/ticket_prices.csv')

In [ ]:
holidays

           date day_tipe holiday_tipe      holiday_name
0    2025-04-01  weekday      holiday  Idulfitri 1446 H
1    2025-04-02  weekday       normal               NaN
2    2025-04-03  weekday       normal               NaN
3    2025-04-04   friday       normal               NaN
4    2025-04-05  weekend       normal               NaN
..          ...      ...          ...               ...
361  2026-03-28  weekend       normal               NaN
362  2026-03-29  weekend       normal               NaN
363  2026-03-30  weekday       normal               NaN
364  2026-03-31  weekday       normal               NaN
365  2026-04-01  weekday       normal               NaN

[366 rows x 4 columns]

In [ ]:
movies

,original_title,age_rating,genre,producer,director,writer,casts
0,120 BAHADUR,Remaja,"Action, War","Farhan Akhtar, Amit Chandrra, Ritesh Sidhwani",Razneesh Ghai,Sumit Arora,"Ankit Siwach, Farhan Akhtar, Amitabh Bachchan,..."
1,"13 DAYS, 13 NIGHTS",Remaja,"Action, War","Dimitri Rassam, Ardavan Safaee",Martin Bourboulon,"Martin Bourboulon, Alexandre Smia, Mohamed Bid...","Roschdy Zem, Lyna Khoudri, Sidse Babett Knudse..."
2,28 YEARS LATER,Dewasa,Thriller,"Danny Boyle, Alex Garland, Peter Rice",Danny Boyle,"Danny Boyle, Alex Garland","Jodie Comer, Aaron Taylor-Johnson, Jack O'Conn..."
3,28 YEARS LATER: THE BONE TEMPLE,Dewasa,Thriller,"Danny Boyle, Alex Garland, Andrew Macdonald",Nia DaCosta,Alex Garland,"Ralph Fiennes, Alfie Williams, Jack O'Connell,..."
4,5 CENTIMETERS PER SECOND (ANIMATION),Remaja,Animation,"Makoto Shinkai, Jin Ho Chung",Makoto Shinkai,Makoto Shinkai,"Kenji Mizuhashi, Yoshimi Kondou, Satomi Hanamu..."
...,...,...,...,...,...,...,...
392,WUTHERING HEIGHTS,Dewasa,"Romance, Drama","Emerald Fennell, Josey McNamara, Margot Robbie",Emerald Fennell,"Emerald Fennell, Emily Bronte","Margot Robbie, Jacob Elordi, Hong Chau, Shazad..."
393,YAKIN NIKAH,Remaja,"Drama, Romance","Shierly Kosasih, Ervina Isleyen",Pritagita Arianegara,"Bene Dion Rajagukguk, Sigit Sulistyo, Erwin Wu","Enzy Storia, Maxime Bouttier, Jourdy Pranata, ..."
394,YOU ARE THE APPLE OF MY EYE,Remaja,"Drama, Romance",Song Dae-chan,Cho Young-myoung,"Giddens Ko, Cho Young-myoung","Jung Jin-young, Kim Da-hyun, Demian, Kim Yo-ha..."
395,YOUR LETTER,Semua Umur,Animation,-,Kim Yong-hwan,Jeong Eun-kyeong,"Lee Suhyun, Kim Min-ju, Min Seung-woo, Nam Doh..."
396,ZOOTOPIA 2,Semua Umur,"Animation, Adventure",Yvett Merino,"Jared Bush, Byron Howard",Jared Bush,"Jason Bateman, Ginnifer Goodwin, Ke Huy Quan, ..."

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_slice = 0.20, random_state = 0)

NameError: name 'X' is not defined

In [ ]:
from sklearn.processing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print ("Hello Woreld")

Hello Woreld